### ISSUE TITLE
Null Pointer Exception Running on Android 4.4.3

### ISSUE THREAD

**Issue by clickslide** [TheMattRay/iBeaconGap#1]
It appears there is an error when the Plugin is attempting to return a value to the JavaScript file. Perhaps I'm missing something in my setup? I'm using Cordova 3.5.0-0.2.4

```
06-13 14:30:58.247: E/PluginManager(16601): java.lang.NullPointerException
06-13 14:30:58.247: E/PluginManager(16601):     at com.thinketg.plugin.ibeacongap.iBeaconGap.execute(iBeaconGap.java:48)
06-13 14:30:58.247: E/PluginManager(16601):     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:65)
06-13 14:30:58.247: E/PluginManager(16601):     at org.apache.cordova.PluginManager.execHelper(PluginManager.java:242)
06-13 14:30:58.247: E/PluginManager(16601):     at org.apache.cordova.PluginManager.exec(PluginManager.java:227)
06-13 14:30:58.247: E/PluginManager(16601):     at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:53)
06-13 14:30:58.247: E/PluginManager(16601):     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
06-13 14:30:58.247: E/PluginManager(16601):     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
06-13 14:30:58.247: E/PluginManager(16601):     at android.os.Handler.dispatchMessage(Handler.java:102)
06-13 14:30:58.247: E/PluginManager(16601):     at android.os.Looper.loop(Looper.java:136)
06-13 14:30:58.247: E/PluginManager(16601):     at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by clickslide** [comment]
I changed line 48 in iBeaconGap.java from:

```
callbackContext.sendPluginResult(new PluginResult(PluginResult.Status.OK, listToJSONArray(myUtil.myBeacons)));
```

To include a "this" reference to the BeaconUtils class:

```
callbackContext.sendPluginResult(new PluginResult(PluginResult.Status.OK, listToJSONArray(this.myUtil.myBeacons)));
```

This does not fix the NullPointerException, however it does fix the failed callback. Now my JavaScript file is receiving the events properly. Although, I have to poll to get results. I've changed my JavaScript file as such:

```
startBeaconScans: function () {
        console.log("Scanning for beacons!");
        setInterval(function(){
            iBeaconGap.getBeacons(app.gotBeacons, app.failedGettingBeacons);
        }, 1000);
    }
```

I do this because the plugin only returns the beacons when you ask for them and onDeviceReady there are no beacons ready for processing. This could easily be changed to trigger the "getBeacons" on a button click instead.

Unfortunately, this issue isn't closed. However, the above hack does work on my Nexus 7 :)

**Comment by TheMattRay** [comment]
Before I forget, I wanted to note that the use of getBeacons to poll the current result set is the intended use and no automatic callback has been implemented. The main reason for this: the bluetooth can call back so rapidly that it paralyzes the app. That being said, I am sure there is a way to thread this out so that it behaves properly, I just have not explored that.

**Comment by TheMattRay** [comment]
Separately, I will look into this. Are you stating that it is specific to 4.4.3 and NOT to prior 4.x releases or is that untested?

**Comment by clickslide** [comment]
Yes, I've only tested it on 4.4.3.
